# Generated by Django 6.0.3 on 2026-03-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('business_owner', 'Business Owner'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
