version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookinghub_db
      POSTGRES_USER: zasmin
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=bookinghub_db
      - DB_USER=zasmin
      - DB_PASSWORD=

volumes:
  postgres_data:
