# Generated by Django 6.0.3 on 2026-05-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('photo', models.URLField(blank=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('languages', models.CharField(max_length=200)),
                ('specialization', models.CharField(choices=[('trekking', 'Trekking'), ('cultural', 'Cultural'), ('history', 'History'), ('nomad', 'Nomad Experience'), ('photography', 'Photography'), ('adventure', 'Adventure')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=1)),
                ('rating', models.FloatField(default=5.0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
