# Generated by Django 6.0.3 on 2026-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='estrictions',
            field=models.TextField(blank=True, help_text='Restrictions, separated by |'),
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.TextField(blank=True, help_text='Why visit - bullet points separated by |'),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included',
            field=models.TextField(blank=True, help_text='What is NOT included, separated by |'),
        ),
    ]
