# Generated by Django 6.0.3 on 2026-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_additional_info_tour_estrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
